name: smaller_png
description: "A new Flutter package project."
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  args: ^2.5.0
  image: ^4.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

executables: 
  smaller_png: bin/smaller_png.dart
